// Code generated by reset generator; DO NOT EDIT.
// generated by cmd/reset
package main

func (r *targetStruct) Reset() {
	if r == nil {
		return
	}

	r.TypeName = ""
	if r.Named != nil {
	}
	if r.Struct != nil {
	}
	r.PkgPath = ""
	r.PkgDir = ""
}
